//const str = "developer";
//const result = str.includes("love");

//console.log(result); // Output: true

//const str = "alpha in turn";
//const result = str.startsWith("alpha");

//console.log(result); // Output: true

//const str = "alphaintern";
//const result = str.endsWith("tern");

//console.log(result); // Output: false

const str = "JavaScript";
const position = str.indexOf('A');

console.log(position); // Output: -1

const sentence = "I am a backend developer.";
const word = "backend";

const isPresent = sentence.includes(word);
console.log(isPresent); // Output: true

