//const str = "alphaintern";
//const newStr = str.replace("intern", "mentor");

//console.log(newStr); ``

//const str = "Banana";
//const result = str.replace(/a/g, "Z");

//console.log(result); 

//const str = " JavaScript is awesome";
//const cleaned = str.trim();

//console.log(cleaned); 
//const str = "alpha intern";
//const extracted = str.slice(6);  

//console.log(extracted); 

const str = "alphaINTERN";
const extracted = str.substring(0, 5);

console.log(extracted); 
